nodeLinker: node-modules

npmRegistryServer: "https://registry.npmmirror.com"

npmScopes:
  tarojs:
    npmRegistryServer: "https://registry.npmmirror.com"
  weapp:
    npmRegistryServer: "https://registry.npmmirror.com"

networkTimeout: 100000
networkConcurrency: 8

cacheFolder: .yarn/cache

enableGlobalCache: false
